name: zariz_app
description: zariz app UI

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  http: ^0.12.0
  shared_preferences: ^0.4.0
  cookie_jar: ^0.0.6
  path_provider: ^0.4.1
  image_picker: ^0.4.10
  utf: ^0.9.0+5
  flutter_google_places_autocomplete: ^0.1.3
  location: ^1.4.1
  google_sign_in: ^3.2.4
  flutter_launcher_icons: ^0.7.0
  firebase_core: ^0.2.5  # add dependency for Firebase Core
  firebase_messaging: ^2.0.0
  firebase_analytics: ^1.0.4
  device_info: ^0.3.0
  latlong: ^0.6.1

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/login_logo.jpg"
dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.jpg
      - assets/no_portrait.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Semibold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
