name: zariz_app
description: zariz app UI

version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  
  http: ^0.12.0
  shared_preferences: ^0.5.7+3
  cookie_jar: ^1.0.1
  path_provider: ^1.6.9
  image_picker: ^0.6.6+4
  utf: ^0.9.0+5
  flutter_google_places_autocomplete: ^0.1.3
  location: ^3.0.2
  google_sign_in: ^4.5.1
  google_maps_flutter: ^0.5.28+1
  flutter_launcher_icons: ^0.7.0
  firebase_core: ^0.4.4+3
  firebase_messaging: ^6.0.15
  #firebase_analytics: ^5.0.11
  device_info: ">=0.4.0 <2.0.0"
  latlong: ^0.6.1
  flutter_facebook_login: ^3.0.0
  flutter_typeahead: ^1.8.5


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/log in_logo.jpg"
dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.jpg
      - assets/no_portrait.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Semibold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
